import {TestBed} from '@angular/core/testing';import {provideHttpClient} from '@angular/common/http';import {HttpTestingController,provideHttpClientTesting} from '@angular/common/http/testing';import {provideRouter} from '@angular/router';import {signal} from '@angular/core';import {of,throwError} from 'rxjs';import {vi} from 'vitest';import {NgForm} from '@angular/forms';import {Checkout} from './checkout';import {CartService} from '../services/cart';import {CustomerApi} from '../services/customer';
describe('Checkout stages',()=>{
 const post=vi.fn();const clear=vi.fn();
 beforeEach(()=>{sessionStorage.removeItem('so-order-retry');post.mockReset();clear.mockReset();TestBed.configureTestingModule({providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting(),{provide:CartService,useValue:{cartItems:signal([{product:{id:1},quantity:1}]),totalPrice:()=>130,canCheckout:signal(true),busy:signal(false),refreshCatalog:()=>{},clearCart:clear}},{provide:CustomerApi,useValue:{session:signal(null),refresh:()=>of({name:'Test',email:'test@example.test'}),post}}]});});
 function setup(){const f=TestBed.createComponent(Checkout);const http=TestBed.inject(HttpTestingController);http.expectOne('/api/orders/payment-methods').flush([{id:'ManualBit',label:'bit',available:true,recipient:'0501234567',recipientName:'Test'}]);http.expectOne('/api/store/shipping').flush({pickupEnabled:true,pickupAddress:'Test',deliveryFee:50,freeDeliveryAbove:500});f.detectChanges();return f;}
 it('does not advance with invalid details or create an order in step one',()=>{const f=setup();f.componentInstance.next({invalid:true} as NgForm);expect(f.componentInstance.step()).toBe(1);f.componentInstance.submit();expect(post).not.toHaveBeenCalled();});
 it('blocks progression and order creation when refreshed stock is unavailable',async()=>{const f=setup();const c=f.componentInstance;const cart=TestBed.inject(CartService);(cart.canCheckout as any).set(false);c.pickup=true;c.phone='0501234567';c.next({invalid:false} as NgForm);expect(c.step()).toBe(1);c.go(2);await c.submit();expect(post).not.toHaveBeenCalled();});
 it('blocks extra phone digits even if submit is called directly',async()=>{const f=setup();const c=f.componentInstance;c.pickup=true;c.phone='050123456789';c.next({invalid:false} as NgForm);expect(c.step()).toBe(1);c.go(2);await c.submit();expect(post).not.toHaveBeenCalled();});
 it('keeps details when returning and displays one payment selection',()=>{const f=setup();const c=f.componentInstance;c.phone='0501234567';c.city='ירושלים';c.street='רחוב הדגמה';c.houseNumber='9';c.next({invalid:false} as NgForm);f.detectChanges();expect(c.step()).toBe(2);expect(f.nativeElement.querySelectorAll('input[name="paymentMethod"]').length).toBe(1);expect(post).not.toHaveBeenCalled();c.go(1);expect(c.address).toBe('ירושלים, רחוב הדגמה 9');});
 it('shows coupon errors at the coupon input instead of the page message',()=>{const f=setup();const c=f.componentInstance;c.go(2);c.couponCode='EXPIRED';post.mockReturnValue(throwError(()=>({error:{message:'תוקף הקופון פג.'}})));c.applyCoupon();f.detectChanges();expect(f.nativeElement.querySelector('.coupon-entry #coupon-error').textContent).toContain('תוקף הקופון פג.');expect(c.message()).toBe('');expect(f.nativeElement.querySelector('#coupon-code').getAttribute('aria-describedby')).toBe('coupon-error');});
 it('keeps optional delivery fields out of pickup requests',async()=>{const f=setup();const c=f.componentInstance;c.pickup=true;c.phone='0501234567';c.postalCode='1234567';c.deliveryNotes='Test note';c.next({invalid:false} as NgForm);post.mockReturnValue(of({id:43,status:'AwaitingPaymentApproval'}));await c.submit();expect(post.mock.calls[0][1].postalCode).toBeNull();expect(post.mock.calls[0][1].deliveryNotes).toBeNull();});
 it('reaches transfer step without presenting a completed payment',async()=>{const f=setup();const c=f.componentInstance;c.phone='0501234567';c.city='ירושלים';c.street='רחוב הדגמה';c.houseNumber='9';c.postalCode='1234567';c.deliveryNotes='  כניסה צדדית  ';c.next({invalid:false} as NgForm);post.mockReturnValue(of({id:42,number:'SO-000042',total:180,status:'AwaitingPaymentApproval',paymentMethod:'ManualBit',paymentRecipient:'0501234567',paymentRecipientName:'Test'}));await c.submit();f.detectChanges();expect(c.step()).toBe(3);expect(c.saved()?.status).toBe('AwaitingPaymentApproval');expect(f.nativeElement.querySelector('[aria-current="step"]').textContent).toContain('העברה ואישור');expect(f.nativeElement.textContent).toContain('ממתינה לאישור תשלום');expect(clear).toHaveBeenCalledOnce();expect(post.mock.calls[0][1].address).toBe('ירושלים, רחוב הדגמה 9');expect(post.mock.calls[0][1].postalCode).toBe('1234567');expect(post.mock.calls[0][1].deliveryNotes).toBe('כניסה צדדית');});
});
 describe('Shipping address fields',()=>{
 it('requires each shipping field and allows an optional apartment',()=>{const c=Object.create(Checkout.prototype) as Checkout;Object.assign(c,{pickup:false,city:' ירושלים ',street:' רחוב הדגמה ',houseNumber:'9א',apartment:'',postalCode:'',deliveryNotes:''});expect(c.validAddress()).toBe(true);expect(c.address).toBe('ירושלים, רחוב הדגמה 9א');c.apartment=' 2 ';expect(c.address).toBe('ירושלים, רחוב הדגמה 9א, דירה 2');c.street=' ';expect(c.validAddress()).toBe(false);c.pickup=true;expect(c.validAddress()).toBe(true);expect(c.address).toBe('');});
});
