import {Component,input,output,signal,computed,DestroyRef,inject} from '@angular/core';
import {Order} from '../services/customer';import {paymentLabel} from '../services/payment-labels';
@Component({selector:'app-manual-payment-instructions',standalone:true,styleUrl:'./manual-payment.css',template:`@if(order();as o){@if(o.reservationExpiresAt&&awaiting(o)){@if(remaining()>0){<p class="reservation-note">המלאי שמור להזמנה זו לעוד <strong dir="ltr">{{countdown()}}</strong>. אישור התשלום בחנות משלים את ההזמנה.</p>}@else{<p class="reservation-note">זמן שמירת המלאי הסתיים. לפני העברה יש לפנות לחנות לבדיקת זמינות. אם כבר שילמתם, נבדוק את המלאי לפני אישור ההזמנה.</p>}}@if(awaiting(o)){<section class="transfer-card" dir="rtl"><p class="transfer-kicker">{{label(o.paymentMethod)}} · העברה ידנית</p><h3>{{o.status==='AwaitingPayment'?'ממתינה לתשלום':'ממתינה לאישור תשלום'}}</h3><dl><div><dt>לתשלום</dt><dd dir="ltr">{{o.total}} ₪</dd></div><div><dt>שם המקבל</dt><dd>{{o.paymentRecipientName}}</dd></div><div><dt>{{o.paymentMethod==='ManualBit'?'מספר bit':'חשבון PayPal'}}</dt><dd dir="ltr">{{o.paymentRecipient}}</dd></div><div><dt>הערה להעברה</dt><dd dir="ltr">{{o.number}}</dd></div></dl>@if(!o.reservationExpiresAt||remaining()>0){<ol><li>יש לפתוח את {{o.paymentMethod==='ManualBit'?'bit':'PayPal'}} ולבחור את מקבל התשלום לפי הפרטים המופיעים למעלה.</li><li>יש להעביר {{o.total}} ₪ ולציין בהערת ההעברה את מספר ההזמנה {{o.number}}.</li><li>יש לשמור את אסמכתת ההעברה עד לאישור התשלום בחנות.</li></ol>}@if(o.paymentMethod==='ManualPayPal'){<p>ב־PayPal יש לבחור תשלום עבור מוצרים ושירותים.</p>}@if(o.status==='AwaitingPayment'){<button type="button" class="declare-paid" (click)="declared.emit()" [disabled]="busy()">{{busy()?'מעדכנים…':'ביצעתי את ההעברה'}}</button><p>יש לסמן רק לאחר ביצוע ההעברה בפועל. הסימון אינו מאשר תשלום; החנות תבדוק שההעברה התקבלה.</p>}@else{<p>ההזמנה ממתינה לאישור קבלת התשלום בחנות. תודה שבחרתם ב־SO — נשמח לטפל בהזמנה שלכם.</p>}</section>}}`})
export class ManualPaymentInstructions{order=input.required<Order>();busy=input(false);declared=output<void>();label=paymentLabel;
 // רק הזמנה במסלול ידני שטרם אושרה מציגה פרטי העברה, כדי שלא תתבקש העברה כפולה.
 awaiting(o:Order){return (o.status==='AwaitingPayment'||o.status==='AwaitingPaymentApproval')&&(o.paymentMethod==='ManualBit'||o.paymentMethod==='ManualPayPal');}
 private now=signal(Date.now());
 remaining=computed(()=>Math.max(0,Math.ceil((Date.parse(this.order().reservationExpiresAt??'')-this.now())/1000))||0);
 countdown=computed(()=>{const s=this.remaining();return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');});
 constructor(){const timer=setInterval(()=>this.now.set(Date.now()),1000);inject(DestroyRef).onDestroy(()=>clearInterval(timer));}
}
